---
- name: Create LTFS Mount Point
  ansible.builtin.file:
    path: "{{ltfs_mount_point}}"
    state: directory
    mode: '0777'

- name: Copy scripts
  template:
    src: '{{ item.src }}'
    dest: '~/{{ item.path }}'
  with_filetree: '../files/scripts'
  when: item.state == 'file'

- name: Copy bash config for default tape device paths
  ansible.builtin.template:
    src: files/etc/profile.d/ltfs_device_variables.sh
    dest: "/etc/profile.d/ltfs_device_variables.sh"
    mode: 0755
