---
# Source: https://unix.stackexchange.com/a/746767
- name: Copy 01-local-power to disable suspend while at login screen
  ansible.builtin.template:
    src: files/etc/dconf/db/gdm.d/01-local-power
    dest: "/etc/dconf/db/gdm.d/01-local-power"

- name: Rebuild dconf database after file added
  ansible.builtin.command:
    cmd: dconf update