---
- name: Hostname
  debug:
    msg: Host is '{{ ansible_facts['hostname'] }}'
- name: OS
  debug:
    msg: OS is '{{ansible_facts['distribution']}} {{ansible_facts['distribution_version']}}'
- name: OS Family
  debug:
    msg: "{{ansible_facts['os_family']}} / {{ansible_facts['distribution_file_variety']}}"

