- name: Linux LTFS Setup
  gather_facts: true
  hosts: ltfs_servers
  become: true
  become_user: root
  vars:
    ltfs_mount_point: /mnt/ltfs

  tasks:
    # - import_tasks: roles/ltfs_servers/tasks/display_system_information.yaml
    # - import_tasks: roles/ltfs_servers/tasks/disable_suspend.yaml
    # - import_tasks: roles/ltfs_servers/tasks/dnf_yum_update.yaml
    # - import_tasks: roles/ltfs_servers/tasks/install_packages.yaml
    - import_tasks: roles/ltfs_servers/tasks/install_linux_ltfs.yaml
    # - import_tasks: roles/ltfs_servers/tasks/configure_ltfs.yaml
    # - import_tasks: roles/ltfs_servers/tasks/install_hpe_ltt.yaml