- name: Linux LTFS Setup
  gather_facts: true
  hosts: ltfs_servers
  become: true
  become_user: root
  vars:
    # This directory will be created and used by mount_ltfs.sh as the a mount
    # point for LTFS tapes.
    ltfs_mount_point: /mnt/ltfs

    # This is the location where the files in files/scripts will be copied to,
    # and it will be added to the default shell path if it's not already there
    # (done in ltfs_device_variables.sh).
    ltfs_scripts_location: /usr/local/bin/

  # "tasks:" is the tasks that will be run on the server hosts. If you want to
  # skip one of these tasks, simply comment it out and it will be ignored
  tasks:
    - import_tasks: roles/ltfs_servers/tasks/display_system_information.yaml
    - import_tasks: roles/ltfs_servers/tasks/disable_suspend.yaml
    - import_tasks: roles/ltfs_servers/tasks/update_installed_packages.yaml
    - import_tasks: roles/ltfs_servers/tasks/install_packages.yaml
    - import_tasks: roles/ltfs_servers/tasks/install_linux_ltfs.yaml
    - import_tasks: roles/ltfs_servers/tasks/configure_ltfs.yaml

    - name: Install hpe_ltt on Redhat-based systems
      ansible.builtin.import_tasks: roles/ltfs_servers/tasks/install_hpe_ltt.yaml
      when: ansible_pkg_mgr == "dnf"