- name: Linux LTFS Setup
  gather_facts: true
  hosts: ltfs_servers
  become: true
  become_user: root
  vars:
    ltfs_mount_point: /mnt/ltfs

  tasks:
    - import_tasks: roles/ltfs_servers/tasks/main.yaml