#!/usr/bin/env bash

export PID_FILE_PATH="ltfs-tape-watcher-service.pid"
export LOG_FILE_PATH="ltfs-tape-watcher-service.log"

. ./services.sh

# Friendly service name (mandatory)
SERVICE_NAME="LTFS Tape Watcher"
# Command to run (mandatory, array variable)
SERVICE_CMD=(ping 1.1.1.1)
# Working Directory (optional)
#SERVICE_WORK_DIR=
# On start (optional, array variable)
#SERVICE_ON_START=()
# On finish (optional, array variable)
#SERVICE_ON_FINISH=()

serviceMenu "$1"
